CREATE TABLE IF NOT EXISTS Employees (
	employee_id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	department INTEGER UNIQUE NOT NULL,
	chief INTEGER UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Chiefs_Emoloyees (
	chief_id INTEGER PRIMARY KEY,
	employee_id INTEGER UNIQUE FOREIGN KEY REFERENCES Employees(chief)
);